#!/bin/bash

# For command 'nvme id-ns /dev/nvme0 -n 1'
python nvme_ns_parser.py -d /dev/nvme0 -c id-ns

# For command 'nvme id-ctrl /dev/nvme0'
python id_ctrl_parser.py -d /dev/nvme0 -c id-ctrl

# use compare.py to compare the result generated by 'nvme' cmd and a given result file
python compare.py -d /dev/nvme0 -c id-ns -args "-n 1" -f old_result

# use nvme_admin_cmd_list.py to run admin cmds several times
python nvme_admin_cmd_list.py -d /dev/nvme0 -m random -n 7  -f lihong_log
python nvme_admin_cmd_list.py -d /dev/nvme0 -m sequential -n 7  -f lihong_log
